apiVersion: ctf.senai.io/v1
kind: Challenge
metadata:
  name: pentest
  version: "1.0.0"
  description: "Desafios de Pentest"
  author: "SENAI"
  difficulty: "hard"
  duration: "120m"
spec:
  environment:
    image: ctf-senai/pentest:latest
    resources:
      cpu: "1"
      memory: "1Gi"
    ports:
      - container: 22
      - container: 80
    credentials:
      user: root
      password: root
  challenges:
    - id: 1
      name: "Weak Password"
      description: "O usuário ctfuser tem uma senha fraca. Use ferramentas de brute force ou wordlists."
      points: 40
      hints:
        - text: "Tente senhas comuns ou use hydra/john. Wordlists em /usr/share/wordlists"
      validation:
        type: "flag"
        flag: "W34K_P4SSW0RD"
        location: "/home/ctfuser/flag.txt"
    - id: 2
      name: "Port Scanning"
      description: "Faça um scan de portas no localhost. Identifique todos os serviços rodando."
      points: 40
      hints:
        - text: "Use nmap, netstat ou ss para escanear portas abertas"
      validation:
        type: "flag"
        flag: "P0RT_SC4NN3R"
        location: "/root/pentest/scan_flag.txt"
    - id: 3
      name: "File Upload"
      description: "Encontre diretórios web com permissões inseguras (777). Verifique /var/www/."
      points: 40
      hints:
        - text: "Use: find /var/www -type d -perm 0777"
      validation:
        type: "flag"
        flag: "UPL04D_VULN"
        location: "/var/www/html/uploads/flag.txt"
    - id: 4
      name: "SQL Injection"
      description: "Analise os scripts em /opt/pentest/. Encontre e teste payloads de SQL Injection."
      points: 40
      hints:
        - text: "Procure por queries SQL. Teste: ' OR '1'='1 -- "
      validation:
        type: "flag"
        flag: "SQL1_M4ST3R"
        location: "/root/pentest/sqli_flag.txt"
    - id: 5
      name: "Reverse Shell"
      description: "Encontre e analise o script de reverse shell em /tmp ou /opt. Identifique IP e porta."
      points: 40
      hints:
        - text: "Procure por arquivos .sh ou .py. Use grep para encontrar 'bash -i' ou 'socket'"
      validation:
        type: "flag"
        flag: "R3V3RS3_SH3LL"
        location: "/root/pentest/revshell_flag.txt"
  scoring:
    total_points: 200
